cp ~/.bash ./.bash
cp ~/.bash_profile ./.bash_profile
cp ~/.bashrc ./.bashrc
cp ~/.gitconfig ./.gitconfig
cp ~/.tmux.conf ./.tmux.conf
cp ~/.zshenv ./.zshenv
cp ~/.zshrc ./.zshrc
cp ~/.atom ./.atom
cp ~/.vscode ./.vscode
